#:schema node_modules/wrangler/config-schema.json
name = "archive-space"
main = "src/index.js"
compatibility_date = "2024-08-21"
compatibility_flags = ["nodejs_compat"]

# [vars]
# MY_VARIABLE = "production_value"

[[r2_buckets]]
binding = "ARCHIVE"
bucket_name = "archive"